apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-homework
  labels:
    app: docker-homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-homework
  template:
    metadata:
      labels:
        app: docker-homework
    spec:
      containers:
        - name: web
          image: homework-k8s-docker:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
